import { createInteractiveSurfaceSpec, type InteractiveSurfaceSpec } from "@sonik-agent-ui/tool-contracts";

export const AMPLIFY_CAMPAIGN_TEMPLATE_CREATE_SURFACE_TEMPLATE: InteractiveSurfaceSpec = createInteractiveSurfaceSpec({
  id: "amplify-campaign-template-create-lite",
  kind: "question_group",
  title: "Create campaign template",
  description: "Collect the minimum campaign facts needed to draft an Amplify campaign template manifest.",
  skillId: "amplify.campaign.template.create",
  state: {
    manifest: {
      manifestType: "amplify_campaign_template",
      status: "draft",
      source: { createdBy: "agent", skill: "amplify.campaign.template.create" },
    },
  },
  questions: [
    {
      id: "q_campaign_goal",
      title: "What is the campaign goal?",
      body: "What outcome should this campaign drive? Examples: bookings, ticket sales, repeat visits, loyalty activation, referrals, or event attendance.",
      answerType: "single_choice",
      required: true,
      allowSkip: false,
      writesTo: "/manifest/campaign/goal",
      choices: [
        { value: "booking_completed", label: "Bookings", description: "Drive completed reservations or appointments." },
        { value: "ticket_sales", label: "Ticket sales", description: "Drive purchases for an event or experience." },
        { value: "repeat_visit", label: "Repeat visits", description: "Bring existing customers back." },
        { value: "loyalty_activation", label: "Loyalty activation", description: "Increase membership, rewards, or wallet behavior." },
        { value: "referral", label: "Referrals", description: "Encourage customers to invite others." },
      ],
    },
    {
      id: "q_campaign_audience",
      title: "Who is the audience?",
      body: "Describe the target audience or segment. Include membership status, location, event interest, loyalty state, or prior behavior if known.",
      answerType: "long_text",
      required: true,
      allowSkip: false,
      writesTo: "/manifest/audience/description",
    },
    {
      id: "q_campaign_channels",
      title: "Where should this run?",
      body: "Which channels should the campaign template support?",
      answerType: "multi_choice",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/channels",
      choices: [
        { value: "email", label: "Email", description: "Email campaign or lifecycle message." },
        { value: "sms", label: "SMS", description: "Text message campaign." },
        { value: "whatsapp", label: "WhatsApp", description: "WhatsApp campaign or concierge flow." },
        { value: "website", label: "Website", description: "Website/banner/page surface." },
        { value: "instagram_dm", label: "Instagram DM", description: "Social DM activation." },
      ],
    },
    {
      id: "q_campaign_offer",
      title: "What is the offer or message?",
      body: "Summarize the offer, hook, or creative brief. If there is no offer, describe the primary message and proof point.",
      answerType: "long_text",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/creative/offerSummary",
    },
  ],
});

export const AMPLIFY_CAMPAIGN_TEMPLATE_CREATE_WORKFLOW = {
  id: "amplify.campaign.template.create",
  title: "Create Amplify campaign template manifest",
  description: "Guide an agent through source copy analysis, structured questions, and draft manifest state for an Amplify campaign template.",
  intentAliases: [
    "create campaign template",
    "create amplify campaign",
    "build campaign manifest",
    "set up campaign wizard",
    "draft campaign template",
    "create marketing campaign",
  ],
  requiredTools: ["ask_user_question", "create_or_update_intake_artifact"],
  optionalTools: ["copy_analyze_retrofit", "manifest_validate", "manifest_export"],
  workflowSteps: [
    "Inspect donated Amplify page context and pasted source copy before asking broad questions.",
    "Create or update a JSON-render campaign intake artifact using the interactiveSurfaceTemplate.",
    "Prioritize goal, audience, channels, offer, creative brief, proof metrics, compliance, and activation path.",
    "Ask only the next highest-impact missing question; preserve unknowns rather than inventing compliance or offer rules.",
    "Keep campaign execution commands preview-only until Phase 5 validation/export and explicit command confirmation exist.",
  ],
  questionPolicy: {
    mode: "progressive_disclosure",
    askStyle: "one_high_impact_question_at_a_time",
    confidenceRequiredForAutofill: 0.75,
    neverInvent: ["offer_terms", "discount", "eligibility", "compliance", "audience_consent", "send_time", "budget"],
  },
  successEvidence: [
    "searchSkillCatalog returns amplify.campaign.template.create for campaign template intent",
    "learnSkill returns campaign question policy and an interactiveSurfaceTemplate with no executable command payload",
    "tool.askUserQuestion/tool.submitQuestionAnswer telemetry can be emitted by the controller when the UI flow runs",
    "artifact.intake.created/artifact.intake.version_created telemetry can be emitted by the artifact persistence seam when wired",
  ],
  telemetryEvents: [
    "tool.searchSkillCatalog",
    "tool.learnSkill",
    "tool.askUserQuestion",
    "tool.submitQuestionAnswer",
    "artifact.intake.created",
    "artifact.intake.version_created",
  ],
  forbiddenUnlessExplicit: [
    "amplify.create.campaign",
    "amplify.send.campaign",
    "amplify.publish.campaign.template",
    "amplify.update.audience.segment",
  ],
  negativeRules: [
    "Do not turn a campaign template answer into approval to publish or send a campaign.",
    "Do not call executeCommand or commitCommand from the JSON renderer or ask-user component.",
    "Do not invent offer terms, discounts, eligibility, compliance, consent, send time, or budget when source material is thin.",
  ],
} as const;
