import { createInteractiveSurfaceSpec, type InteractiveSurfaceSpec } from "@sonik-agent-ui/tool-contracts";

export const BOOKING_CONTEXT_INTAKE_SURFACE_TEMPLATE: InteractiveSurfaceSpec = createInteractiveSurfaceSpec({
  id: "booking-context-intake-lite",
  kind: "question_group",
  title: "Create booking context",
  description: "Collect the operational facts needed to draft a bookable venue schedule, resource, and service-period manifest.",
  skillId: "booking.context.intake",
  state: {
    manifest: {
      manifestType: "venue_schedule",
      status: "draft",
      source: { createdBy: "agent", skill: "booking.context.intake" },
    },
  },
  questions: [
    {
      id: "q_intake_mode",
      title: "What are we configuring?",
      body: "Are we creating a recurring venue schedule, a one-time event, or a hybrid event with bookable sub-inventory?",
      whyThisMatters: "This controls which manifest fields and command previews become relevant later.",
      answerType: "choice_cards",
      required: true,
      allowSkip: false,
      writesTo: "/manifest/intakeMode",
      choices: [
        { value: "venue_schedule", label: "Venue schedule", description: "Recurring inventory such as tee times, tables, rooms, classes, rentals, or appointments." },
        { value: "event", label: "Event", description: "A specific time-bound experience such as a concert, dinner, workshop, or tournament." },
        { value: "hybrid", label: "Hybrid", description: "An event that also has bookable sub-inventory such as VIP tables, sessions, rooms, or add-ons." },
      ],
    },
    {
      id: "q_inventory_core",
      title: "What can customers book, reserve, buy, or request?",
      body: "List the core inventory in plain language. Examples: tee times, dinner reservations, VIP tables, private lessons, rooms, sessions, rentals, tickets, or add-ons.",
      answerType: "long_text",
      required: true,
      allowSkip: false,
      writesTo: "/manifest/inventory/coreDescription",
    },

    {
      id: "q_open_days",
      title: "Which days are open for reservations?",
      body: "Select every day this venue accepts reservations. If hours differ by day, note the exceptions in the operating hours question next.",
      whyThisMatters: "Open days drive the schedule rules and prevent the agent from inventing recurring availability.",
      answerType: "multi_choice",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/schedule/openDays",
      choices: [
        { value: "monday", label: "Monday" },
        { value: "tuesday", label: "Tuesday" },
        { value: "wednesday", label: "Wednesday" },
        { value: "thursday", label: "Thursday" },
        { value: "friday", label: "Friday" },
        { value: "saturday", label: "Saturday" },
        { value: "sunday", label: "Sunday" },
      ],
    },
    {
      id: "q_operating_hours",
      title: "What are the operating hours?",
      body: "Describe the reservation window in plain language, including exceptions if any. Example: Tuesday through Sunday, 9am to 5pm.",
      answerType: "long_text",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/schedule/operatingHoursDescription",
    },
    {
      id: "q_table_layout",
      title: "What tables, rooms, or resources can be reserved?",
      body: "Describe the table/resource layout and capacities. Example: tables 1-10 are 2-tops, 11-20 are 4-tops, 21-25 are 6-tops.",
      whyThisMatters: "This becomes the capacity and resource map before any booking context can be created.",
      answerType: "long_text",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/inventory/tableLayoutDescription",
    },
    {
      id: "q_service_periods",
      title: "Do different service periods need different rules or menus?",
      body: "List service periods such as breakfast, lunch, dinner, brunch, or special seatings, with their times. Example: breakfast 9-11, lunch 11-4, dinner 4-5.",
      answerType: "long_text",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/schedule/servicePeriodsDescription",
    },
    {
      id: "q_menu_requirements",
      title: "Which menus or offer sets are needed?",
      body: "Select menus that need separate copy, pricing, or fulfillment rules. Add details later if any menu needs review.",
      answerType: "multi_choice",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/menus/required",
      choices: [
        { value: "breakfast", label: "Breakfast" },
        { value: "lunch", label: "Lunch" },
        { value: "dinner", label: "Dinner" },
        { value: "brunch", label: "Brunch" },
        { value: "drinks", label: "Drinks" },
        { value: "special_event", label: "Special event" },
      ],
    },
    {
      id: "q_confirmation_mode",
      title: "How should bookings be confirmed?",
      body: "Should customers receive instant confirmation, require manual approval, join a waitlist, or submit a request before staff confirms?",
      whyThisMatters: "This prevents the agent from inventing approval, waitlist, or payment behavior.",
      answerType: "single_choice",
      required: false,
      allowSkip: true,
      skipValue: "unknown",
      writesTo: "/manifest/inventory/confirmationMode",
      choices: [
        { value: "instant_confirm", label: "Instant confirmation", description: "Customer can book immediately if inventory is available." },
        { value: "manual_approval", label: "Manual approval", description: "Staff must approve before the booking is confirmed." },
        { value: "deposit_then_confirm", label: "Deposit then confirm", description: "Customer pays a deposit, then confirmation happens by policy." },
        { value: "request_to_book", label: "Request to book", description: "Customer submits a request without immediate confirmation." },
        { value: "waitlist", label: "Waitlist", description: "Customer joins a waitlist when capacity is unavailable." },
      ],
    },
  ],
});

export const BOOKING_CONTEXT_INTAKE_WORKFLOW = {
  id: "booking.context.intake",
  title: "Create booking context intake",
  description: "Guide an agent through source copy analysis, structured questions, and draft manifest state for a reusable booking context.",
  intentAliases: [
    "create booking context",
    "create bookable context",
    "set up booking context",
    "build intake manifest",
    "configure venue schedule",
    "create event context",
  ],
  requiredTools: ["ask_user_question", "create_or_update_intake_artifact"],
  optionalTools: ["copy_analyze_retrofit", "manifest_validate", "manifest_export"],
  workflowSteps: [
    "Inspect donated page context and any pasted source copy before asking broad questions.",
    "Create or update a JSON-render intake artifact using the interactiveSurfaceTemplate; use the deterministic schedule, resource/table, service-period, and menu questions instead of improvising a new generic artifact.",
    "Ask only the next highest-impact missing question; preserve unknowns rather than inventing policy.",
    "Write answers into artifact state through the trusted question-answer controller only.",
    "Keep command execution as preview-only until a later validation/export/confirmation phase maps answers to trusted ORPC commands.",
  ],
  questionPolicy: {
    mode: "progressive_disclosure",
    askStyle: "one_high_impact_question_at_a_time",
    confidenceRequiredForAutofill: 0.75,
    neverInvent: ["pricing", "refund_policy", "cancellation_policy", "capacity", "payment_required", "legal_terms", "guest_access_rules"],
  },
  successEvidence: [
    "searchSkillCatalog returns booking.context.intake for booking context creation intent",
    "learnSkill returns question policy and an interactiveSurfaceTemplate with no executable command payload",
    "tool.askUserQuestion/tool.submitQuestionAnswer telemetry can be emitted by the controller when the UI flow runs",
    "venue schedule artifacts include deterministic open-days, operating-hours, table/resource-layout, service-period, and menu-requirement fields",
    "artifact.intake.created/artifact.intake.version_created telemetry can be emitted by the artifact persistence seam when wired",
  ],
  telemetryEvents: [
    "tool.searchSkillCatalog",
    "tool.learnSkill",
    "tool.askUserQuestion",
    "tool.submitQuestionAnswer",
    "artifact.intake.created",
    "artifact.intake.version_created",
  ],
  forbiddenUnlessExplicit: [
    "booking.create.booking",
    "booking.create.hold",
    "booking.create.schedule.rule",
    "booking.create.pricing.rule",
  ],
  negativeRules: [
    "Do not turn an intake answer into approval for a booking write command.",
    "Do not call executeCommand or commitCommand from the JSON renderer or ask-user component.",
    "Do not invent pricing, refund, cancellation, capacity, payment, or legal policy when source material is thin.",
  ],
} as const;
