import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const pageSource = await readFile("apps/standalone-sveltekit/src/routes/+page.svelte", "utf8");
const rootSource = await readFile("packages/workspace-core/src/components/WorkspaceRoot.svelte", "utf8");
const generateRoute = await readFile("apps/standalone-sveltekit/src/routes/api/generate/+server.ts", "utf8");
const streamTelemetrySource = await readFile("apps/standalone-sveltekit/src/lib/server/stream-telemetry.ts", "utf8");
const devSmokeStreamSource = await readFile("apps/standalone-sveltekit/src/lib/server/dev-smoke-stream.ts", "utf8");
const commandCatalogToolsSource = await readFile("apps/standalone-sveltekit/src/lib/tools/command-catalog.ts", "utf8");
const hostCommandRuntimeSource = await readFile("apps/standalone-sveltekit/src/lib/server/host-command-runtime.ts", "utf8");
const sessionRailSource = await readFile("apps/standalone-sveltekit/src/lib/session/SessionRail.svelte", "utf8");
const sessionDetailRoute = await readFile("apps/standalone-sveltekit/src/routes/api/session/[id]/+server.ts", "utf8");
const sessionMessagesRoute = await readFile("apps/standalone-sveltekit/src/routes/api/session/[id]/messages/+server.ts", "utf8");
const documentToolsSource = await readFile("apps/standalone-sveltekit/src/lib/tools/document.ts", "utf8");
const workspaceSessionSource = await readFile("packages/workspace-session/src/index.ts", "utf8");
const sessionsRoute = await readFile("apps/standalone-sveltekit/src/routes/api/sessions/+server.ts", "utf8");
const appCss = await readFile("apps/standalone-sveltekit/src/app.css", "utf8");
const layoutSource = await readFile("apps/standalone-sveltekit/src/routes/+layout.svelte", "utf8");
const workspaceFrameSource = await readFile("packages/workspace-core/src/components/WorkspaceDocumentFrame.svelte", "utf8");
const workspaceHostSource = await readFile("apps/standalone-sveltekit/static/workspace-document-host.html", "utf8");
const agentMessageSource = await readFile("packages/chat-surface/src/components/AgentMessage.svelte", "utf8");
const agentConversationSource = await readFile("packages/chat-surface/src/components/AgentConversation.svelte", "utf8");
const chatTextSource = await readFile("packages/chat-surface/src/components/ChatText.svelte", "utf8");
const chatTextParserSource = await readFile("packages/chat-surface/src/chat-text.ts", "utf8");
const chatSurfaceIndexSource = await readFile("packages/chat-surface/src/index.ts", "utf8");
const chatMessagePartsSource = await readFile("packages/chat-surface/src/message-parts.ts", "utf8");
const canvasViewportSource = await readFile("packages/workspace-core/src/components/CanvasViewport.svelte", "utf8");
const themeRuntimeSource = await readFile("apps/standalone-sveltekit/src/lib/theme/theme-runtime.ts", "utf8");
const themePickerSource = await readFile("apps/standalone-sveltekit/src/lib/theme/ThemePicker.svelte", "utf8");
const themeRegistrySource = await readFile("apps/standalone-sveltekit/src/lib/theme/theme-registry.ts", "utf8");
const daisyThemeSource = await readFile("apps/standalone-sveltekit/src/lib/theme/foundations/themes/daisy.css", "utf8");

assert.equal(rootSource.includes("rail?: Snippet"), true, "WorkspaceRoot should expose an optional rail snippet");
assert.equal(rootSource.includes("{@render rail()}"), true, "WorkspaceRoot should render the session rail beside chat/artifacts");
assert.equal(rootSource.includes('data-has-rail={Boolean(rail)}'), true, "WorkspaceRoot should keep no-rail integrations compatible");

assert.equal(pageSource.includes("let sessions = $state<WorkspaceSessionSummary[]>([])"), true, "app shell should keep a visible session list state");
assert.equal(pageSource.includes("let archivedSessionCount = $state(0)"), true, "app shell should make archived chat behavior visible");
assert.equal(pageSource.includes("let activeSessionId = $state<string | null>(null)"), true, "app shell should track active session id");
assert.equal(pageSource.includes("/api/sessions"), true, "app shell should load session summaries from the session API");
assert.equal(pageSource.includes("/api/session/${encodeURIComponent(sessionId)}/messages"), true, "app shell should persist chat history by session");
assert.equal(pageSource.includes("{#snippet rail()}"), true, "top-level app should provide the WorkspaceRoot rail slot");
assert.equal(pageSource.includes("sessionId: activeSessionId"), true, "generate requests should carry active session id");
assert.equal(pageSource.includes("function deriveChatTitle"), true, "app shell should derive deterministic first-message chat titles locally");
assert.equal(pageSource.includes("maybeNameNewChat(trimmed)"), true, "app shell should name new chats before sending the first message");
assert.equal(pageSource.includes('method: "PATCH"'), true, "app shell should call the session rename route");
assert.equal(pageSource.includes('method: "DELETE"'), true, "app shell should call the session delete route");
assert.equal(pageSource.includes("logSessionTelemetry"), true, "session rail actions should emit telemetry for debugging manual tests");
assert.equal(pageSource.includes("void loadArchivedSessionCount()"), true, "archived chat count should be best-effort and not block active session bootstrap");
assert.equal(pageSource.includes("session.archive_count.error"), true, "archived count failures should be observable without breaking active sessions");
assert.equal(pageSource.includes("session.archive.success"), true, "archiving a chat should be observable in telemetry");
assert.equal(pageSource.includes("normalizePersistedParts"), true, "session switching should hydrate persisted message parts back into chat");
assert.equal(pageSource.includes("archivedCount={archivedSessionCount}"), true, "rail should receive archived session count");
assert.equal(pageSource.includes("<SessionRail"), true, "top-level app should delegate rail presentation to a bounded shell component");
assert.equal(sessionRailSource.includes("onclick={() => onSwitch(session.id)}"), true, "session rail should expose session switching control");
assert.equal(sessionRailSource.includes("disabled={busy || session.id === activeSessionId}"), true, "session rail should disable switches during busy/streaming transitions");
assert.equal(sessionRailSource.includes("oncontextmenu={(event) => openContextMenu(event, session)}"), true, "session rail should expose right-click session actions");
assert.equal(sessionRailSource.includes("onclick={archiveContextSession}"), true, "session rail should expose archive through the context menu");
assert.equal(sessionRailSource.includes("onclick={deleteContextSession}"), true, "session rail should expose delete through the context menu");
assert.equal(sessionRailSource.includes("disabled={busy}"), true, "session rail should disable context menu actions during busy/streaming transitions");
assert.equal(sessionRailSource.includes("session-meta"), false, "session rail rows should stay slim and avoid card-style metadata clutter");
assert.equal(sessionRailSource.includes("{archivedCount} archived"), true, "session rail should show archived chat count instead of silently losing archived records");
assert.equal(sessionRailSource.includes("formatSessionTime"), true, "session rail should own session timestamp formatting");
assert.equal(pageSource.includes("Stop the current stream before switching sessions."), true, "session switches should be guarded while a stream is active");
assert.equal(pageSource.includes("tryFlushPendingDocumentPersistence"), true, "session transitions should hard-gate on document snapshot flushes");
assert.equal(pageSource.includes("sessionRailBusy = true;\n    sessionRailError = null;\n    try {\n      await flushPendingDocumentPersistence()"), true, "session transitions should acquire the rail lock before flushing document snapshots");
assert.equal(pageSource.includes("throw new Error(message || \"Document changes could not be saved; session transition was blocked.\")"), true, "failed document PATCH should throw instead of fail-open");
assert.equal(pageSource.includes("startDocumentPersistenceWorker"), true, "document snapshots should persist through a serialized worker");
assert.equal(pageSource.includes("void documentPersistPromise.catch(() => undefined)"), true, "background document persistence errors should be captured without unhandled rejections");
assert.equal(pageSource.includes("if (!failed && pendingDocumentSnapshot) startDocumentPersistenceWorker()"), true, "new snapshots arriving during a successful flush should be persisted next");
assert.equal(pageSource.includes("if (pendingDocumentSnapshot && createDocumentSnapshotSignature(pendingDocumentSnapshot) === signature)"), true, "in-flight document PATCHes should only clear the same snapshot they persisted");
assert.equal(pageSource.includes("scheduleDocumentPersistence(event.document)"), true, "document frame events should persist snapshots outside generate turns");

assert.equal(sessionDetailRoute.includes("getWorkspaceSession(params.id)"), true, "session detail route should resolve one session by id");
assert.equal(sessionDetailRoute.includes("listWorkspaceMessages(session.id)"), true, "session detail route should return message history");
assert.equal(sessionDetailRoute.includes("activeDocument"), true, "session detail route should hydrate the active document");
assert.equal(sessionDetailRoute.includes("listWorkspaceTelemetryEvents(session.id).slice(-50)"), true, "session detail route should expose bounded telemetry for debugging");
assert.equal(sessionDetailRoute.includes("export async function PATCH"), true, "session detail route should support renaming chats");
assert.equal(sessionDetailRoute.includes("patchWorkspaceSession(session.id, { name })"), true, "session rename route should patch only the validated session name");
assert.equal(sessionDetailRoute.includes("export function DELETE"), true, "session detail route should support deleting local chats");
assert.equal(sessionDetailRoute.includes("deleteWorkspaceSession(session.id)"), true, "session delete route should use the persistence seam");
assert.equal(sessionDetailRoute.includes('persistence: "ephemeral-v0"'), true, "session detail route should make v0 JSON artifact ephemerality explicit");
assert.equal(sessionDetailRoute.includes("listWorkspaceToolCalls"), false, "session detail route should not advertise unhydrated tool-call state in v0");
assert.equal(sessionDetailRoute.includes("listWorkspaceLayoutSnapshots"), false, "session detail route should not advertise unhydrated layout state in v0");

assert.equal(sessionMessagesRoute.includes("appendWorkspaceMessage"), true, "message route should persist chat messages through workspace adapter");
assert.equal(sessionMessagesRoute.includes("listWorkspaceMessages(session.id)"), true, "message route should read chat messages through workspace adapter");
assert.equal(sessionMessagesRoute.includes("WORKSPACE_CONTENT_MAX_CHARS"), true, "message persistence should apply route limits to content");
assert.equal(sessionMessagesRoute.includes("Invalid JSON message payload"), true, "message route should reject malformed JSON instead of appending blank messages");
assert.equal(sessionMessagesRoute.includes("role must be system, user, assistant, or tool"), true, "message route should reject invalid roles instead of defaulting to assistant");

assert.equal(generateRoute.includes("workspace.sessionId"), true, "generate route should validate workspace session id");
assert.equal(generateRoute.includes("activeDocument?.session_id ?? workspaceSessionId"), true, "generate telemetry should prefer active document session and fall back to shell session");
assert.equal(generateRoute.includes("includeHostRuntime: true"), true, "generate route should opt into host-composed command indexes without changing the neutral default helper");
assert.equal(generateRoute.includes('hostSessionMode: "standalone-demo"'), true, "generate route should opt into fixture host auth explicitly instead of relying on hidden trusted defaults");
assert.equal(generateRoute.includes("createAgent({ activeDocument, sessionId: telemetrySessionId, pageContext })"), true, "agent tools should receive active workspace session id and page context");
assert.equal(commandCatalogToolsSource.includes("executeHostCatalogCommand"), true, "command catalog tools should execute through the host runtime adapter seam");
assert.equal(commandCatalogToolsSource.includes("createStandaloneHostCommandRuntimeBundle"), true, "command catalog tools should compose host catalog/runtime adapters for standalone smoke testing");
assert.equal(commandCatalogToolsSource.includes('hostSessionMode: "standalone-demo"'), true, "command catalog tools should use the explicit standalone demo host-session adapter for local smoke testing");
assert.equal(commandCatalogToolsSource.includes("searchCommandCatalogWithMetadata(catalog, query, 50)"), true, "command catalog search should rank context-loaded commands before slicing to the requested limit");
assert.equal(commandCatalogToolsSource.includes(".slice(0, boundedLimit)"), true, "command catalog search should apply the requested limit after context-aware ranking");
assert.equal(commandCatalogToolsSource.includes("contextLoadedCommandIds"), true, "command catalog search should expose page-context-loaded command ids separately from global lazy discovery");
assert.equal(commandCatalogToolsSource.includes("contextLoaded: contextCommandIds.has(commandId)"), true, "learnCommand should reveal whether a command was loaded by the current page context");
assert.equal(commandCatalogToolsSource.includes("policyReasons: receipt.policy.reasons"), true, "command execution telemetry should include policy reasons for manual debugging");
assert.equal(commandCatalogToolsSource.includes("runtimeProvider: receipt.trace.provider"), true, "command execution telemetry should include runtime provider provenance");
assert.equal(hostCommandRuntimeSource.includes("STANDALONE_DEMO_BOOKING_CONTEXTS_COMMAND_ID"), true, "standalone host runtime should expose a stable manual-smoke booking command id");
assert.equal(hostCommandRuntimeSource.includes("fixtureOnly: true"), true, "standalone host runtime must label demo data as fixture-only");
assert.equal(hostCommandRuntimeSource.includes("resolveStandaloneHostSession"), true, "standalone host runtime should resolve an explicit host session envelope before composing host commands");
assert.equal(hostCommandRuntimeSource.includes("createEmbeddedHostSessionEnvelope"), true, "standalone host runtime should include an Amplify-shaped embedded host session path");
assert.equal(hostCommandRuntimeSource.includes("filterEligibleHostCommandAdapters"), true, "host command composition should be gated by adapter-owned trusted auth/org/scope eligibility");
assert.equal(hostCommandRuntimeSource.includes("isEligible:"), true, "host adapters should own their own eligibility rule instead of hardcoding one global family gate");

assert.equal(documentToolsSource.includes("sessionId?: string | null"), true, "document tool context should accept a workspace session id");
assert.equal(documentToolsSource.includes("session_id: runtime.sessionId"), true, "new document artifacts should be created inside the active workspace session");
assert.equal(workspaceSessionSource.includes("deleteSession(id: string): boolean"), true, "workspace session adapter should expose explicit session deletion");
assert.equal(workspaceSessionSource.includes("this.#messages.delete(id)"), true, "session deletion should remove local message history");

assert.equal(sessionsRoute.includes('url.searchParams.get("archived") === "true"'), true, "session list API should expose archived session records for future archive views");
assert.equal(appCss.includes('@source "../../../packages/chat-surface/dist"'), true, "Tailwind should scan packaged chat surface Svelte output");
assert.equal(appCss.includes('@import "./lib/theme/foundations/themes/daisy.css"'), true, "standalone app should import the copied Amplify/Daisy theme foundation");
assert.equal(appCss.includes("--color-background: var(--color-base-100)"), true, "standalone app should map copied Daisy theme vars into shadcn-style aliases");
assert.equal(appCss.includes("--app-control-bg"), true, "standalone app should project canonical theme vars into local app control vars");
assert.equal(appCss.includes("--sonik-border-color"), true, "standalone app should expose a compatibility border color without shadowing DaisyUI border width");
assert.equal(appCss.includes("--border: color-mix"), false, "standalone app should not overwrite DaisyUI\'s --border width token as a color");
assert.equal(daisyThemeSource.includes('themes: all'), true, "DaisyUI should compile the full built-in theme library");
assert.equal(themeRegistrySource.includes('CUSTOM_DOCUMENT_THEME_IDS'), true, "theme registry should include Amplify custom themes");
assert.equal(themeRegistrySource.includes('DAISY_BUILTIN_THEME_IDS'), true, "theme registry should expose DaisyUI built-in themes");
assert.equal(themeRuntimeSource.includes('THEME_STORAGE_KEY = "amplify.documentTheme"'), true, "theme runtime should use the Amplify theme storage key");
assert.equal(themeRuntimeSource.includes('DEFAULT_THEME_SETTING: ThemeSetting = "system"'), true, "standalone app should not hardcode a gunmetal default and should support system preference");
assert.equal(themeRuntimeSource.includes('THEME_CHANGE_EVENT = "amplify:document-theme-change"'), true, "theme runtime should emit the Amplify theme change event");
assert.equal(layoutSource.includes("initializeTheme()"), true, "layout should initialize through the shared theme runtime instead of hand-writing data-theme");
assert.equal(pageSource.includes("<ThemePicker />"), true, "chat shell should expose a theme picker in the global actions");
assert.equal(themePickerSource.includes('<option value="system">System</option>'), true, "theme picker should allow system preference");
assert.equal(workspaceFrameSource.includes("sonik:workspace-document:theme"), true, "document iframe wrapper should send theme tokens to the workspace document island");
assert.equal(workspaceFrameSource.includes("targetOrigin?: string"), true, "document iframe theme bridge should make its postMessage target origin explicit for host adapters");
assert.equal(workspaceFrameSource.includes("allowedOrigin?: string"), true, "document iframe wrapper should make inbound message origin explicit for host adapters");
assert.equal(workspaceHostSource.includes("parentTargetOrigin = event.origin"), true, "workspace document host should reply to the parent origin it received");
assert.equal(workspaceHostSource.includes("const allowedParentOrigin = window.location.origin"), true, "bundled workspace document host should reject arbitrary cross-origin embedding parents");
assert.equal(workspaceHostSource.includes("if (event.origin !== allowedParentOrigin) return"), true, "workspace document host should validate parent origin before processing commands");
assert.equal(workspaceHostSource.includes("document_host.theme_applied"), true, "workspace document host should apply and log theme bridge events");
assert.equal(workspaceHostSource.includes("'--bg': payload.background"), true, "workspace document host should bridge canonical app theme vars into workspace native vars");
assert.equal(workspaceHostSource.includes("'--panel': panel"), true, "workspace document host should bridge panel colors into workspace native vars");
assert.equal(agentMessageSource.includes("chat-bubble"), false, "chat message display should not use Daisy chat-bubble wrappers that add bubble tails");
assert.equal(agentMessageSource.includes("MessagePrimitive"), false, "chat message display should not use Daisy chat primitives for flat Claude-style rows");
assert.equal(agentMessageSource.includes("<ChatText"), true, "chat messages should render text through the safe rich-text renderer");
assert.equal(agentMessageSource.includes("white-space: pre-wrap"), true, "user-authored chat text should preserve multiline prompt fidelity");
assert.equal(agentMessageSource.includes("function snapshotDataParts"), false, "chat messages should import the shared data-part snapshot helper instead of duplicating clone logic");
assert.equal(chatMessagePartsSource.includes("export function snapshotDataParts"), true, "chat surface should own a reusable data-part snapshot helper");
assert.equal(chatSurfaceIndexSource.includes("snapshotDataParts"), true, "chat surface should export data-part snapshot helper for app-shell promotion/persistence paths");
assert.equal(chatTextParserSource.includes("parseTable"), true, "chat text renderer should present markdown tables instead of leaving raw pipes in chat");
assert.equal(chatTextSource.includes("{@html"), false, "chat text renderer should avoid HTML injection and render structured Svelte elements");
assert.equal(canvasViewportSource.includes("documentTitle"), true, "artifact canvas should accept document title metadata for document-only mode");
assert.equal(canvasViewportSource.includes("Document editor active"), true, "artifact canvas should expose a document-aware subtitle when no JSON artifact is promoted");
assert.equal(generateRoute.includes("instrumentGenerateStream"), true, "generate route should wrap the AI stream with completion/failure telemetry");
assert.equal(streamTelemetrySource.includes("api.generate.stream_finished"), true, "generate stream helper should log normal stream completion");
assert.equal(streamTelemetrySource.includes("api.generate.stream_failed"), true, "generate stream helper should log stream failures before surfacing them");
assert.equal(streamTelemetrySource.includes("api.generate.stream_cancelled"), true, "generate stream helper should log stream cancellation for manual stop/debugging");

assert.equal(pageSource.includes("chat.activity.status"), true, "client should expose sanitized activity status telemetry without raw reasoning");
assert.equal(pageSource.includes("Waiting for model response"), true, "chat UI should show a sanitized wait status for long silent model spans");
assert.equal(pageSource.includes("formatToolActivityDetail"), true, "tool activity details should be human labels instead of raw tool slugs");
assert.equal(pageSource.includes("detail: activity.detail,"), false, "activity telemetry signature should not emit every second during long waits");
assert.equal(pageSource.includes("activity={agentActivity}"), true, "top-level app should pass activity status into the chat surface");
assert.equal(agentConversationSource.includes("AgentActivityStatus"), true, "chat surface should define a reusable activity status contract");
assert.equal(agentConversationSource.includes("data-tone={activity.tone"), true, "chat surface should render the activity tone without exposing reasoning text");
assert.equal(streamTelemetrySource.includes("api.generate.stream_waiting"), true, "server stream telemetry should log sanitized long-wait spans");
assert.equal(streamTelemetrySource.includes("api.generate.stream_first_visible_text"), true, "server stream telemetry should log first visible text latency");
assert.equal(streamTelemetrySource.includes("api.generate.stream_first_tool"), true, "server stream telemetry should log first tool latency");
assert.equal(streamTelemetrySource.includes("api.generate.stream_first_artifact_spec"), true, "server stream telemetry should log first artifact spec latency");
assert.equal(streamTelemetrySource.includes("reasoning"), false, "stream telemetry milestones should not expose raw reasoning content or reasoning counts to users");
assert.equal(generateRoute.includes("dropped_reasoning"), false, "generate telemetry should not expose hidden reasoning counters in log reason strings");
assert.equal(generateRoute.includes("stream_safety_filter_applied"), true, "generate telemetry should report sanitized stream safety application");
assert.equal(streamTelemetrySource.includes("runId: context.runId"), true, "generate stream helper should keep smoke/test run correlation on terminal stream events");
assert.equal(streamTelemetrySource.includes(".catch(() => undefined)"), true, "generate stream helper telemetry should be best-effort and non-throwing");
assert.equal(generateRoute.includes("devSmokeMockStream"), false, "generate route should not expose deterministic smoke mode as a general request-body command");
assert.equal(generateRoute.includes("shouldUseDevSmokeStream(request)"), true, "generate route should gate deterministic smoke mode from request headers only");
assert.equal(devSmokeStreamSource.includes("DEV_SMOKE_STREAM_HEADER"), true, "dev smoke stream should live in a named server adapter instead of inline route logic");
assert.equal(devSmokeStreamSource.includes("api.generate.dev_smoke_stream"), true, "dev smoke stream should emit explicit telemetry proving the mock path was used");
assert.equal(generateRoute.includes("await writeDevSmokeStreamTelemetry(smokeInput)"), true, "generate route should write deterministic smoke telemetry before returning the smoke stream so the gate is not race-prone");
assert.equal(devSmokeStreamSource.includes("runId"), true, "dev smoke stream should carry run correlation into stream telemetry");
assert.equal(layoutSource.includes('window.addEventListener("error", handleError)'), true, "layout should capture browser runtime errors into telemetry");
assert.equal(layoutSource.includes('window.addEventListener("unhandledrejection", handleUnhandledRejection)'), true, "layout should capture browser unhandled promise rejections into telemetry");
assert.equal(layoutSource.includes("client.runtime.error"), true, "client runtime errors should have a stable telemetry event name");
assert.equal(layoutSource.includes("client.runtime.unhandledrejection"), true, "client unhandled rejections should have a stable telemetry event name");
assert.equal(layoutSource.includes("RUNTIME_ERROR_MAX_CHARS"), true, "client runtime telemetry should bound error payload size before browser logging/posting");
assert.equal(pageSource.includes("document_artifact.promote_error"), true, "document promotion effect failures should be logged instead of crashing silently");
assert.equal(pageSource.includes("json_artifact.promote_error"), true, "JSON artifact promotion effect failures should be logged instead of crashing silently");
assert.equal(pageSource.includes("session.messages.persist_start"), true, "post-stream message persistence should log start events");
assert.equal(pageSource.includes("session.messages.persist_success"), true, "post-stream message persistence should log success events");
assert.equal(pageSource.includes("session.messages.persist_error"), true, "post-stream message persistence should log failure events");
assert.equal(pageSource.includes("session.messages.persist_unhandled"), true, "post-stream persistence promises should not become invisible unhandled rejections");

const agentTelemetrySource = await readFile("apps/standalone-sveltekit/src/lib/server/agent-telemetry.ts", "utf8");
const telemetryRouteSource = await readFile("apps/standalone-sveltekit/src/routes/api/telemetry/+server.ts", "utf8");
const pageContextRouteSource = await readFile("apps/standalone-sveltekit/src/routes/api/dev/page-context/+server.ts", "utf8");
const observabilityPackageSource = await readFile("packages/agent-observability/src/index.ts", "utf8");
const evidenceServerSource = await readFile("scripts/agent-ui-dev-evidence-server.mjs", "utf8");
const smokeHarnessSource = await readFile("scripts/agent-ui-smoke.mjs", "utf8");
const packageSource = await readFile("package.json", "utf8");
assert.equal(observabilityPackageSource.includes("AGENT_UI_TELEMETRY_SCHEMA_VERSION"), true, "shared observability core should publish a stable telemetry schema version");
assert.equal(observabilityPackageSource.includes("Runtime-safe page-control surface"), true, "page-control contract should document that it is a runtime-safe host seam, not an unbounded dev-only global");
assert.equal(observabilityPackageSource.includes("sanitizeTelemetryValue"), true, "shared observability core should provide redaction before logs become machine evidence");
assert.equal(agentTelemetrySource.includes("sanitizeTelemetryEvent"), true, "server telemetry writer should use shared observability sanitization");
assert.equal(telemetryRouteSource.includes('record.source === "' + "ody" + 'sseus-host"'), false, "telemetry API should not keep legacy copied-editor branding as a first-class source name");
assert.equal(telemetryRouteSource.includes('return "workspace-host"'), true, "telemetry API should normalize legacy host source names to workspace-host");
assert.equal(telemetryRouteSource.includes('value === "server"'), false, "browser telemetry route should not accept forged privileged server source events");
assert.equal(telemetryRouteSource.includes('value === "system"'), false, "browser telemetry route should not accept forged privileged system source events");
assert.equal(generateRoute.includes("createTelemetryCorrelation"), true, "generate route should create or trust correlation headers per request");
assert.equal(generateRoute.includes('"x-sonik-request-id"'), true, "generate route should return machine-readable request correlation headers");
assert.equal(generateRoute.includes("traceparent"), true, "generate route should propagate W3C traceparent evidence");
assert.equal(pageSource.includes("chat.stream.lifecycle"), true, "client should log streaming lifecycle transitions for browser-side crash triage");
assert.equal(pageSource.includes("session.messages.persist_eligible"), true, "client should log when streamed messages become eligible for persistence");
assert.equal(pageSource.includes("__SONIK_AGENT_UI_PAGE_CONTEXT__"), true, "client should expose page context to local browser smoke tests");
assert.equal(pageSource.includes("__sonikAgentUI"), true, "client should expose the canonical Sonik Agent UI page-control contract");
assert.equal(pageSource.includes("getPageContext: snapshotPageContext"), true, "page-control contract should expose snapshot-only page context");
assert.equal(pageSource.includes("getAssertions: snapshotAssertions"), true, "page-control contract should expose snapshot-only assertions");
assert.equal(pageSource.includes("$state.snapshot"), true, "page-control snapshots should avoid exposing live Svelte state proxies");
assert.equal(pageSource.includes("submitPrompt"), true, "page-control contract should expose a semantic submit action backed by existing handlers");
assert.equal(pageSource.includes("function getSubmitDisabledReason"), true, "page-control submit and manual submit should share one disabled-reason gate");
assert.equal(pageSource.includes("createDevSmokeHeaders"), true, "dev smoke mode should be transported as headers from the local smoke URL");
assert.equal(pageSource.includes("devSmokeMockStream"), false, "page should not put smoke-only mode flags into the application request body");
assert.equal(pageSource.includes("openWorkspaceDocument"), true, "page-control contract should expose document host action without DOM scraping");
assert.equal(pageSource.includes("lastPersistStatus"), true, "page assertions should track post-stream persistence state for crash regression gates");
assert.equal(pageContextRouteSource.includes("client.page_context.updated"), true, "dev page context endpoint should persist a telemetry breadcrumb");
assert.equal(pageContextRouteSource.includes("Dev page context is disabled"), true, "dev page context endpoint should be gated outside local/dev observability mode");
assert.equal(pageSource.includes("if (!dev) return"), true, "client page context posting should be disabled outside SvelteKit dev mode");
assert.equal(evidenceServerSource.includes("/events"), true, "local evidence server should expose telemetry as machine-readable JSON");
assert.equal(evidenceServerSource.includes("127.0.0.1"), true, "local evidence server should bind to loopback by default");
assert.equal(evidenceServerSource.includes('access-control-allow-origin"] = origin'), true, "local evidence server should echo only allowed localhost origins instead of wildcard CORS");
assert.equal(evidenceServerSource.includes("AGENT_UI_EVIDENCE_ALLOW_LAN"), true, "local evidence server LAN exposure should be explicit opt-in");
assert.equal(evidenceServerSource.includes("/stream"), true, "local evidence server should expose an SSE tail for future live log streaming");
assert.equal(smokeHarnessSource.includes('page.on("crash"'), true, "smoke harness should explicitly catch browser page crashes");
assert.equal(smokeHarnessSource.includes("x-sonik-request-id"), true, "smoke harness should verify generate correlation headers");
assert.equal(smokeHarnessSource.includes("window.__sonikAgentUI"), true, "smoke harness should require canonical page-control state/actions instead of DOM synthesis");
assert.equal(smokeHarnessSource.includes("api.generate.stream_finished"), true, "smoke harness should require server stream completion telemetry");
assert.equal(smokeHarnessSource.includes("api.generate.dev_smoke_stream"), true, "smoke harness should prove deterministic smoke mode was actually used");
assert.equal(smokeHarnessSource.includes("serverDevSmokeStream"), true, "smoke harness should classify deterministic smoke telemetry separately from stream finish");
assert.equal(smokeHarnessSource.includes("requestIds"), true, "smoke harness should correlate stream telemetry to same-run generate response ids");
assert.equal(smokeHarnessSource.includes("AGENT_UI_SMOKE_ALLOW_INCONCLUSIVE"), true, "smoke harness should fail inconclusive infrastructure results unless explicitly opted out");
assert.equal(smokeHarnessSource.includes("session.messages.persist_success"), true, "smoke harness should require client message persistence telemetry after streaming");
assert.equal(smokeHarnessSource.includes("AGENT_UI_SMOKE_START_SERVER"), true, "smoke harness should be batteries-included and able to start local dev dependencies");
assert.equal(packageSource.includes("smoke:agent-ui:real-model"), true, "package scripts should expose an explicit real-model smoke lane separate from deterministic crash gating");

const artifactToolSource = await readFile("apps/standalone-sveltekit/src/lib/tools/artifact.ts", "utf8");
assert.equal(artifactToolSource.includes("validateSpec"), true, "artifact tool should use shared json-render structural validation");
assert.equal(artifactToolSource.includes("explorerCatalog.validate"), true, "artifact tool should validate against the component catalog");
assert.equal(artifactToolSource.includes("Object.keys(elements).length > 0"), true, "artifact tool schema should reject empty elements maps");
assert.equal(artifactToolSource.includes("spec.elements must include the root key"), true, "artifact tool schema should require root to exist in elements");
assert.equal(artifactToolSource.includes("tool.createJsonArtifact.rejected_invalid_spec"), true, "invalid artifact specs should be rejected as tool errors, not promoted as recovered successes");
assert.equal(artifactToolSource.includes("recovered_invalid_spec"), false, "artifact tool should not report recovered invalid specs as successful artifact outputs");
assert.equal(artifactToolSource.includes("Never call this with { \"elements\": {} }"), true, "artifact tool description should explicitly forbid empty spec elements");

console.log("app-shell-session-rail tests passed");
